'use client'

import { useState, useEffect } from 'react'
import { createClient } from '@/lib/supabase/client'
import WellnessTipCard from '@/components/WellnessTipCard'
import styles from './wellness.module.css'

const MOOD_EMOJI = { 1: '😔', 2: '😟', 3: '😐', 4: '🙂', 5: '😊' }

export default function WellnessPage() {
  const [tips, setTips] = useState([])
  const [source, setSource] = useState('')
  const [loading, setLoading] = useState(true)
  const [profile, setProfile] = useState(null)
  const [recentMoods, setRecentMoods] = useState([])
  const supabase = createClient()

  useEffect(() => {
    async function load() {
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) return

      const [{ data: prof }, { data: checkins }] = await Promise.all([
        supabase.from('profiles').select('*').eq('id', user.id).single(),
        supabase.from('mood_checkins').select('mood_score, stress_triggers, created_at')
          .eq('user_id', user.id).order('created_at', { ascending: false }).limit(3),
      ])

      setProfile(prof)
      setRecentMoods(checkins || [])

      const moodScores = (checkins || []).map(c => c.mood_score)
      const stressTriggers = checkins?.[0]?.stress_triggers || []

      if (moodScores.length === 0) {
        // No check-ins yet — show generic medium tips
        const res = await fetch('/api/wellness', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ examType: prof?.exam_type || 'exams', moodScores: [3], stressTriggers: [] }),
        })
        const data = await res.json()
        setTips(data.tips)
        setSource(data.source)
      } else {
        const res = await fetch('/api/wellness', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ examType: prof?.exam_type, moodScores, stressTriggers }),
        })
        const data = await res.json()
        setTips(data.tips)
        setSource(data.source)
      }

      setLoading(false)
    }
    load()
  }, [])

  async function regenerate() {
    setLoading(true)
    const { data: { user } } = await supabase.auth.getUser()
    const { data: checkins } = await supabase
      .from('mood_checkins').select('mood_score, stress_triggers')
      .eq('user_id', user.id).order('created_at', { ascending: false }).limit(3)

    const res = await fetch('/api/wellness', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        examType: profile?.exam_type,
        moodScores: (checkins || []).map(c => c.mood_score),
        stressTriggers: checkins?.[0]?.stress_triggers || [],
      }),
    })
    const data = await res.json()
    setTips(data.tips)
    setSource(data.source)
    setLoading(false)
  }

  return (
    <div className="animate-in">
      <div className="page-header flex justify-between items-center" style={{ flexWrap: 'wrap', gap: '12px' }}>
        <div>
          <h1>Wellness Tips ✨</h1>
          <p>
            {source === 'gemini' ? 'AI-personalized just for you' : 'Curated tips based on your mood'}
            {recentMoods.length > 0 && ` • Based on your recent moods: ${recentMoods.map(c => MOOD_EMOJI[c.mood_score]).join(' ')}`}
          </p>
        </div>
        <button id="regenerate-btn" className="btn btn-ghost" onClick={regenerate} disabled={loading}>
          🔄 Refresh Tips
        </button>
      </div>

      {loading ? (
        <div className={styles.loading}>
          <div className={styles.spinner} />
          <p>Generating personalized tips for your {profile?.exam_type || 'exam'} journey…</p>
        </div>
      ) : (
        <div className={styles.tips}>
          {tips.map((tip, i) => <WellnessTipCard key={i} tip={tip} index={i} />)}
        </div>
      )}

      {!loading && source === 'gemini' && (
        <p className={styles.aiNote}>✦ These tips were generated by AI based on your recent check-ins. Always consult a professional for serious mental health concerns.</p>
      )}
    </div>
  )
}
